import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { HospitalProvider } from "@/context/hospital-context";
import { DoctorProvider } from "@/context/doctor-context";
import { PatientProvider } from "@/context/patient-context";
import { AgendaProvider } from "@/context/agenda-context";
import { ProcedureProvider } from "@/context/procedure-context";

import AppLayout from "@/components/layout/app-layout";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <HospitalProvider>
          <DoctorProvider>
            <PatientProvider>
              <AgendaProvider>
                <ProcedureProvider>
                  <AppLayout>
                    {children}
                  </AppLayout>
                </ProcedureProvider>
              </AgendaProvider>
            </PatientProvider>
          </DoctorProvider>
        </HospitalProvider>
      </body>
    </html>
  );
}
