import { Hospital, Doctor, Patient, Surgery, Procedure } from "@/types";

export const MOCK_SURGERIES: Surgery[] = [
    {
        id: "1",
        patientId: "1",
        patientName: "Ana Oliveira",
        doctorId: "1",
        doctorName: "Dr. Roberto Almeida",
        hospitalId: "1",
        hospitalName: "Hospital Santa Casa de Misericórdia",
        procedure: "Colecistectomia Videolaparoscópica",
        date: "2025-12-17",
        startTime: "07:30",
        endTime: "09:00",
        room: "Sala 03",
        status: "completed",
        createdAt: new Date().toISOString()
    },
    {
        id: "2",
        patientId: "2",
        patientName: "Carlos Santos",
        doctorId: "2",
        doctorName: "Dra. Luciana Mendes",
        hospitalId: "3",
        hospitalName: "Hospital Sírio-Libanês",
        procedure: "Hernioplastia Inguinal",
        date: "2025-12-17",
        startTime: "09:30",
        endTime: "11:00",
        room: "Sala 01",
        status: "in_progress",
        createdAt: new Date().toISOString()
    },
    {
        id: "3",
        patientId: "99", // Mock non-existing
        patientName: "Carla Dias",
        doctorId: "99",
        doctorName: "Dr. Felipe",
        hospitalId: "99",
        hospitalName: "Hospital Moinhos de Vento",
        procedure: "Rinoplastia Estruturada",
        date: "2025-12-17",
        startTime: "11:30",
        endTime: "13:30",
        room: "Sala 02",
        status: "scheduled",
        createdAt: new Date().toISOString()
    },
    {
        id: "4",
        patientId: "98",
        patientName: "Osvaldo Cruz",
        doctorId: "98",
        doctorName: "Dr. Mendes",
        hospitalId: "98",
        hospitalName: "Hospital Santa Catarina",
        procedure: "Artroplastia Total de Joelho",
        date: "2025-12-18",
        startTime: "14:00",
        endTime: "16:00",
        room: "Sala 04",
        status: "scheduled",
        createdAt: new Date().toISOString()
    },
    {
        id: "5",
        patientId: "97",
        patientName: "João Lucas",
        doctorId: "1",
        doctorName: "Dr. Roberto Almeida",
        hospitalId: "2",
        hospitalName: "Hospital Albert Einstein",
        procedure: "Apendicectomia",
        date: "2025-12-18",
        startTime: "16:30",
        endTime: "18:00",
        room: "Sala 03",
        status: "scheduled",
        createdAt: new Date().toISOString()
    },
    ...Array.from({ length: 50 }).map((_, i) => ({
        id: `mock-surg-${i + 6}`,
        patientId: `mock-pat-${i + 3}`,
        patientName: `Paciente ${i + 3}`,
        doctorId: `mock-doc-${(i % 5) + 3}`,
        doctorName: `Dr. Mock ${i + 3}`,
        hospitalId: `mock-${(i % 5) + 4}`,
        hospitalName: `Hospital Geral ${(i % 5) + 1}`,
        procedure: "Procedimento Padrão",
        date: "2025-12-20",
        startTime: "08:00",
        endTime: "10:00",
        room: "Sala 01",
        status: "scheduled" as const,
        createdAt: new Date().toISOString()
    }))
];

export const MOCK_PATIENTS: Patient[] = [
    {
        id: "1",
        name: "Ana Oliveira",
        insurance: "Unimed",
        plan: "Nacional",
        birthDate: "1985-04-12",
        gender: "female",
        number: "123",
        complement: "",
        neighborhood: "Jardim das Flores",
        city: "São Paulo",
        state: "SP",
        cep: "01000-000",
        street: "Rua das Flores",
        phone: "(11) 98765-4321",
        email: "ana.oliveira@email.com",
        createdAt: new Date().toISOString()
    },
    {
        id: "2",
        name: "Carlos Santos",
        insurance: "Bradesco",
        plan: "Top",
        birthDate: "1978-09-23",
        gender: "male",
        cep: "01310-100",
        street: "Av. Paulista",
        number: "1000",
        complement: "Apto 50",
        neighborhood: "Bela Vista",
        city: "São Paulo",
        state: "SP",
        phone: "(11) 91234-5678",
        createdAt: new Date().toISOString()
    },
    ...Array.from({ length: 50 }).map((_, i) => ({
        id: `mock-pat-${i + 3}`,
        name: `Paciente Teste ${i + 1}`,
        insurance: "Particular",
        plan: "Básico",
        birthDate: "1990-01-01",
        gender: "male" as const,
        cep: "00000-000",
        street: "Rua Teste",
        number: "100",
        complement: "",
        neighborhood: "Centro",
        city: "São Paulo",
        state: "SP",
        phone: "(11) 99999-9999",
        createdAt: new Date().toISOString()
    }))
];

export const MOCK_DOCTORS: Doctor[] = [
    {
        id: "1",
        crm: "123456",
        name: "Dr. Roberto Almeida",
        specialty: "Cardiologia",
        status: "active",
        createdAt: new Date("2024-01-15").toISOString(),
        updatedAt: new Date("2024-03-20").toISOString()
    },
    {
        id: "2",
        crm: "654321",
        name: "Dra. Luciana Mendes",
        specialty: "Ortopedia",
        status: "active",
        createdAt: new Date("2024-02-10").toISOString(),
        updatedAt: new Date("2024-02-10").toISOString()
    },
    ...Array.from({ length: 50 }).map((_, i) => ({
        id: `mock-doc-${i + 3}`,
        crm: `${100000 + i}`,
        name: `Dr. Especialista ${i + 1}`,
        specialty: "Cirurgia Geral",
        status: "active" as const,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }))
];

export const MOCK_HOSPITALS: Hospital[] = [
    {
        id: "1",
        name: "Hospital Santa Casa de Misericórdia",
        phone: "(11) 3224-0000",
        email: "contato@santacasasp.org.br",
        cep: "01221-020",
        street: "R. Dr. Cesário Mota Jr.",
        number: "112",
        complement: "",
        neighborhood: "Vila Buarque",
        city: "São Paulo",
        state: "SP",
        referencePoint: "Próximo ao Mackenzie",
        createdAt: new Date().toISOString()
    },
    {
        id: "2",
        name: "Hospital Albert Einstein",
        phone: "(11) 2151-1233",
        email: "atendimento@einstein.br",
        cep: "05652-900",
        street: "Av. Albert Einstein",
        number: "627",
        complement: "Bloco A1",
        neighborhood: "Morumbi",
        city: "São Paulo",
        state: "SP",
        referencePoint: "Entrada principal",
        createdAt: new Date().toISOString()
    },
    {
        id: "3",
        name: "Hospital Sírio-Libanês",
        phone: "(11) 3394-0200",
        email: "sac@sirio-libanes.org.br",
        cep: "01308-050",
        street: "Rua Dona Adma Jafet",
        number: "91",
        complement: "",
        neighborhood: "Bela Vista",
        city: "São Paulo",
        state: "SP",
        referencePoint: "",
        createdAt: new Date().toISOString()
    },
    ...Array.from({ length: 50 }).map((_, i) => ({
        id: `mock-${i + 4}`,
        name: `Hospital Geral ${i + 1}`,
        phone: `(11) 3000-${(1000 + i).toString().slice(1)}`,
        email: `contato@hospitalgeral${i + 1}.com.br`,
        cep: `0${1000 + i * 10}-000`,
        street: `Rua Exemplo ${i + 1}`,
        number: `${(i + 1) * 10}`,
        complement: "",
        neighborhood: "Centro",
        city: "São Paulo",
        state: "SP",
        referencePoint: "",
        createdAt: new Date().toISOString()
    }))
];

export const MOCK_PROCEDURES: Procedure[] = [
    {
        id: '1',
        code: '30201012',
        name: 'Apendicectomia',
        specialty: 'Cirurgia Geral',
        fastingTime: '8 horas',
        estimatedDuration: '60 min',
        anesthesiaType: 'Geral',
        equipment: 'Videolaparoscópio',
        materials: 'Grampeadores',
        bloodRequirement: 'Não',
        teamSize: 'Cirurgião, Auxiliar, Instrumentador, Anestesista',
        recoveryTimePACU: '60 min',
        recoveryTimeICU: '0',
        hospitalizationTime: '24 horas',
        homeRecoveryTime: '15 dias',
        suggestedCertificateTime: '15 dias',
        consentForm: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        reports: [],
    },
    {
        id: '2',
        code: '30713131',
        name: 'Artroplastia Total de Joelho',
        specialty: 'Ortopedia',
        fastingTime: '8 horas',
        estimatedDuration: '120 min',
        anesthesiaType: 'Raqui',
        equipment: 'Intensificador de imagem',
        materials: 'Prótese Joelho',
        bloodRequirement: 'Reserva 1CH',
        teamSize: '2 Cirurgiões, Instrumentador, Anestesista',
        recoveryTimePACU: '120 min',
        recoveryTimeICU: '24 horas',
        hospitalizationTime: '3 dias',
        homeRecoveryTime: '45 dias',
        suggestedCertificateTime: '60 dias',
        consentForm: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        reports: [],
    },
    {
        id: '3',
        code: '30713131',
        name: 'Artroplastia Total de Joelho',
        specialty: 'Ortopedia',
        fastingTime: '8 horas',
        estimatedDuration: '120 min',
        anesthesiaType: 'Raqui',
        equipment: 'Intensificador de imagem',
        materials: 'Prótese Joelho',
        bloodRequirement: 'Reserva 1CH',
        teamSize: '2 Cirurgiões, Instrumentador, Anestesista',
        recoveryTimePACU: '120 min',
        recoveryTimeICU: '24 horas',
        hospitalizationTime: '3 dias',
        homeRecoveryTime: '45 dias',
        suggestedCertificateTime: '60 dias',
        consentForm: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        reports: [],
    },
    ...Array.from({ length: 50 }).map((_, i) => ({
        id: `mock-proc-${i + 3}`,
        code: `${30000000 + i}`,
        name: `Procedimento Mock ${i + 1}`,
        specialty: i % 2 === 0 ? 'Cirurgia Geral' : 'Ortopedia',
        fastingTime: '8 horas',
        estimatedDuration: '90 min',
        anesthesiaType: 'Geral',
        equipment: 'Padrão',
        materials: 'Kit Padrão',
        bloodRequirement: 'Não',
        teamSize: 'Equipe Padrão',
        recoveryTimePACU: '60 min',
        recoveryTimeICU: '0',
        hospitalizationTime: '24 horas',
        homeRecoveryTime: '10 dias',
        suggestedCertificateTime: '14 dias',
        consentForm: i % 3 !== 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        reports: []
    }))
];
